version: 2
jobs:
  build:
    working_directory: ~/vgs-proxy-spring
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - vgs-proxy-spring-{{ checksum "lib/pom.xml" }}
      - run: mvn clean install -Dsurefire.useSystemClassLoader=false
      - save_cache:
          key: vgs-proxy-spring-{{ checksum "lib/pom.xml" }}
          paths:
            - ~/.m2
